# Generated by Django 3.0 on 2019-12-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='testPost',
        ),
    ]
