# Generated by Django 3.0 on 2019-12-26 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20191219_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='post2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=3)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
