# Generated by Django 3.0 on 2019-12-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_post2'),
    ]

    operations = [
        migrations.CreateModel(
            name='id_ap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
