# Generated by Django 3.0 on 2019-12-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_id_ap'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_ap',
            name='ticket',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
