# Generated by Django 3.0 on 2019-12-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20191230_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='id_ap',
            old_name='session',
            new_name='ticket',
        ),
    ]
