# Generated by Django 3.0 on 2019-12-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20191230_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='id_ap',
            old_name='account',
            new_name='idname',
        ),
        migrations.RemoveField(
            model_name='id_ap',
            name='password',
        ),
        migrations.RemoveField(
            model_name='id_ap',
            name='ticket',
        ),
        migrations.AddField(
            model_name='id_ap',
            name='uid',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
