# Generated by Django 3.0 on 2020-01-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20200102_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='megall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meg_text', models.CharField(max_length=30)),
            ],
        ),
    ]
