# Generated by Django 3.0 on 2020-01-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_megall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megall',
            name='meg_text',
            field=models.CharField(max_length=200),
        ),
    ]
