# Generated by Django 3.0 on 2020-01-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_auto_20200102_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='megall',
            name='uid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
