# Generated by Django 3.0 on 2020-01-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_megall_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='megall',
            old_name='uid',
            new_name='user_uid',
        ),
    ]
